# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula")

class AndroidBuildTools2200 < AndroidToolFormula
  url "https://dl.google.com/android/repository/build-tools_r22-macosx.zip"
  version "22.0.0"
  sha1 "af95429b24088d704bc5db9bd606e34ac1b82c0d"

  depends_on "toonetown/android/android-sdk"
  depends_on "toonetown/android/android-platform-tools"

  def install
    (prefix/"build-tools"/version).install Dir["*"]
    install_tools prefix/"build-tools"/version

    link_sdk_dir "build-tools"
  end

  test do
    system "true"
  end
end
