# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula")

class AndroidLldb20 < AndroidToolFormula
  desc "LLDB 2.0"
  url "https://dl.google.com/android/repository/lldb-2.0.2558144-darwin-x86_64.zip"
  version "2.0.2558144"
  sha1 "d92e2f4c8284413eed4f27986e62b167d947033c"

  depends_on "toonetown/android/android-sdk"
  depends_on "toonetown/android/android-ndk"

  def install
    (prefix/"lldb"/"2.0").install Dir["*"]
    install_tools prefix/"lldb"/"2.0"

    pkg_xml = prefix/"lldb"/"2.0"/"package.xml"
    pkg_xml.delete if pkg_xml.exist?
    pkg_xml.write <<-EOS.undent
      <ns4:repository xmlns:ns4="http://schemas.android.com/repository/android/common/01">
        <localPackage obsolete="false" path="lldb;2.0">
          <revision>
            <major>#{version.to_s.split(".")[0]}</major>
            <minor>#{version.to_s.split(".")[1]}</minor>
            <micro>#{version.to_s.split(".")[2]}</micro>
          </revision>
          <display-name>#{desc}</display-name>
        </localPackage>
      </ns4:repository>
    EOS

    link_sdk_dir "lldb"
  end

  test do
    system "true"
  end
end
