# This file is autogenerated by the generate-sdks.sh script

require 'pathname'
require Pathname(__FILE__).realpath.dirname.join('../lib', 'android-tool-formula')

class AndroidBuildTools1902 < AndroidToolFormula
  url 'https://dl-ssl.google.com/android/repository/build-tools_r19.0.2-macosx.zip'
  version '19.0.2'
  sha1 '145bc43065d45f756d99d87329d899052b9a9288'

  depends_on "toonetown/android/android-sdk"
  depends_on "toonetown/android/android-platform-tools"

  def install
    (prefix/"build-tools"/version).install Dir["*"]
    install_tools prefix/"build-tools"/version

    link_sdk_dir "build-tools"
  end
  
end
