# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula")

class AndroidBuildTools2302 < AndroidToolFormula
  url "https://dl.google.com/android/repository/build-tools_r23.0.2-macosx.zip"
  version "23.0.2"
  sha1 "482c4cbceef8ff58aefd92d8155a38610158fdaf"

  depends_on "toonetown/android/android-sdk"
  depends_on "toonetown/android/android-platform-tools"

  def install
    (prefix/"build-tools"/version).install Dir["*"]
    install_tools prefix/"build-tools"/version

    link_sdk_dir "build-tools"
  end
end
