# This file is autogenerated by the generate-sdks.sh script

require 'pathname'
require Pathname(__FILE__).realpath.dirname.join('../lib', 'android-ndk-formula')

class AndroidNdk < AndroidNdkFormula
  url 'https://dl.google.com/android/repository/android-ndk-r11c-darwin-x86_64.zip'
  version '11c'
  sha1 '4ce8e7ed8dfe08c5fe58aedf7f46be2a97564696'
end
