# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula")

class AndroidLldb21 < AndroidToolFormula
  desc "LLDB 2.1"
  url "https://dl.google.com/android/repository/lldb-2.1.2852477-darwin-x86_64.zip"
  version "2.1.2852477"
  sha1 "d1e33880a53f1aa8c7e73534adef83a06f091185"

  depends_on "toonetown/android/android-sdk"
  depends_on "toonetown/android/android-ndk"

  def install
    (prefix/"lldb"/"2.1").install Dir["*"]
    install_tools prefix/"lldb"/"2.1"

    pkg_xml = prefix/"lldb"/"2.1"/"package.xml"
    pkg_xml.delete if pkg_xml.exist?
    pkg_xml.write <<-EOS.undent
      <ns4:repository xmlns:ns4="http://schemas.android.com/repository/android/common/01">
        <localPackage obsolete="false" path="lldb;2.1">
          <revision>
            <major>#{version.to_s.split(".")[0]}</major>
            <minor>#{version.to_s.split(".")[1]}</minor>
            <micro>#{version.to_s.split(".")[2]}</micro>
          </revision>
          <display-name>#{desc}</display-name>
        </localPackage>
      </ns4:repository>
    EOS

    link_sdk_dir "lldb"
  end

  test do
    system "true"
  end
end
