# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula")

class AndroidBuildTools1811 < AndroidToolFormula
  url "https://dl.google.com/android/repository/build-tools_r18.1.1-macosx.zip"
  version "18.1.1"
  sha1 "a9d9d37f6ddf859e57abc78802a77aaa166e48d4"

  depends_on "toonetown/android/android-sdk"
  depends_on "toonetown/android/android-platform-tools"

  def install
    (prefix/"build-tools"/version).install Dir["*"]
    install_tools prefix/"build-tools"/version

    link_sdk_dir "build-tools"
  end

  test do
    system "true"
  end
end
