# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula") unless defined?(android_tool_formula)

class AndroidLldb22 < AndroidToolFormula
  desc "LLDB 2.2"
  url "https://dl.google.com/android/repository/lldb-2.2.3094112-darwin-x86_64.zip"
  version "2.2.3094112"
  sha1 "0eda822b304ca18f0cde8091e337b89458cec6a4"

  depends_on "toonetown/android/android-sdk"
  depends_on "toonetown/android/android-ndk"

  def install
    (prefix/"lldb"/"2.2").install Dir["*"]
    install_tools prefix/"lldb"/"2.2"

    pkg_xml = prefix/"lldb"/"2.2"/"package.xml"
    pkg_xml.delete if pkg_xml.exist?
    pkg_xml.write <<-EOS.undent
      <ns4:repository xmlns:ns4="http://schemas.android.com/repository/android/common/01">
        <localPackage obsolete="false" path="lldb;2.2">
          <revision>
            <major>#{version.to_s.split(".")[0]}</major>
            <minor>#{version.to_s.split(".")[1]}</minor>
            <micro>#{version.to_s.split(".")[2]}</micro>
          </revision>
          <display-name>#{desc}</display-name>
        </localPackage>
      </ns4:repository>
    EOS

    link_sdk_dir "lldb"
  end

  test do
    system "true"
  end
end
