# This file is autogenerated by the generate-sdks.sh script

require 'pathname'
require Pathname(__FILE__).realpath.dirname.join('../lib', 'android-tool-formula')

class AndroidM2repository < AndroidToolFormula
  url 'https://dl.google.com/android/repository/android_m2repository_r30.zip'
  version '30.0.0'
  sha1 'a06aadc0a32f1cd1c44e8004385929b17425fc37'
  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"extras/android/m2repository").install Dir["*"]
    install_tools prefix/"extras/android/m2repository"

    srcProp = prefix/"extras/android/m2repository/source.properties"
    srcProp.delete if srcProp.exist?
    srcProp.write <<-EOS.undent
      Extra.VendorId=android
      Extra.Path=m2repository
      Pkg.Revision=#{version}
    EOS

    link_sdk_dir "extras/android"
  end
  
end
