# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula") unless defined?(android_tool_formula)

class AndroidBuildTools2603 < AndroidToolFormula
  url "https://dl.google.com/android/repository/build-tools_r26.0.3-macosx.zip"
  version "26.0.3"
  sha1 "5bb90ed935d99e5bc90686f43b852e68c5ad40df"

  depends_on "toonetown/android/android-sdk"
  depends_on "toonetown/android/android-platform-tools"

  def install
    (prefix/"build-tools"/version).install Dir["*"]
    install_tools prefix/"build-tools"/version

    link_sdk_dir "build-tools"
  end

  test do
    system "true"
  end
end
