# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula") unless defined?(android_tool_formula)

class AndroidLldb23 < AndroidToolFormula
  desc "LLDB 2.3"
  url "https://dl.google.com/android/repository/lldb-2.3.3614996-darwin-x86_64.zip"
  version "2.3.3614996"
  sha1 "6b0df112c7b9fa41654497fde2fcce990c831e52"

  depends_on "toonetown/android/android-sdk"
  depends_on "toonetown/android/android-ndk"

  def install
    (prefix/"lldb"/"2.3").install Dir["*"]
    install_tools prefix/"lldb"/"2.3"

    pkg_xml = prefix/"lldb"/"2.3"/"package.xml"
    pkg_xml.delete if pkg_xml.exist?
    pkg_xml.write <<-EOS.undent
      <ns4:repository xmlns:ns4="http://schemas.android.com/repository/android/common/01">
        <localPackage obsolete="false" path="lldb;2.3">
          <revision>
            <major>#{version.to_s.split(".")[0]}</major>
            <minor>#{version.to_s.split(".")[1]}</minor>
            <micro>#{version.to_s.split(".")[2]}</micro>
          </revision>
          <display-name>#{desc}</display-name>
        </localPackage>
      </ns4:repository>
    EOS

    link_sdk_dir "lldb"
  end

  test do
    system "true"
  end
end
