# This file is autogenerated by the generate-sdks.sh script

require 'pathname'
require Pathname(__FILE__).realpath.dirname.join('../lib', 'android-tool-formula')

class AndroidSupport < AndroidToolFormula
  url 'http://dl-ssl.google.com/android/repository/support_r23.zip'
  version '23.0.0'
  sha1 'ebdbd0c1c1b051d5ceac55e6f0bd59775707214c'
  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"extras/android/support").install Dir["*"]
    install_tools prefix/"extras/android/support"

    srcProp = prefix/"extras/android/support/source.properties"
    srcProp.delete if srcProp.exist?
    srcProp.write <<-EOS.undent
      Extra.VendorId=android
      Extra.Path=support
      Pkg.Revision=#{version}
    EOS

    link_sdk_dir "extras/android"
  end
  
end
