# This file is autogenerated by the generate-sdks.sh script

require 'pathname'
require Pathname(__FILE__).realpath.dirname.join('../lib', 'android-tool-formula')

class AndroidPlatformTools < AndroidToolFormula
  url 'http://dl-ssl.google.com/android/repository/platform-tools_r23-macosx.zip'
  version '23.0.0'
  sha1 '1403fa0d1bb57ec31170d7905e8505e3b0ed05ee'

  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"platform-tools").install Dir["*"]
    install_tools prefix/"platform-tools"

    link_sdk_dir "platform-tools"
  end
  
end
