# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula")

class AndroidBuildTools2101 < AndroidToolFormula
  url "https://dl.google.com/android/repository/build-tools_r21.0.1-macosx.zip"
  version "21.0.1"
  sha1 "b60c8f9b810c980abafa04896706f3911be1ade7"

  depends_on "toonetown/android/android-sdk"
  depends_on "toonetown/android/android-platform-tools"

  def install
    (prefix/"build-tools"/version).install Dir["*"]
    install_tools prefix/"build-tools"/version

    link_sdk_dir "build-tools"
  end
end
