# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula") unless defined?(android_tool_formula)

class AndroidPlatformTools < AndroidToolFormula
  url "https://dl.google.com/android/repository/platform-tools_r25.0.4-darwin.zip"
  version "25.0.4"
  sha1 "e129a1cb9f5e03807e19881bf0b02f0971cb1dc2"

  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"platform-tools").install Dir["*"]
    install_tools prefix/"platform-tools"

    link_sdk_dir "platform-tools"
  end

  test do
    system "true"
  end
end
