# This file is autogenerated by the generate-sdks.sh script

require 'pathname'
require Pathname(__FILE__).realpath.dirname.join('../lib', 'android-ndk-formula')

class AndroidNdk < AndroidNdkFormula
  url 'http://dl-ssl.google.com/android/repository/android-ndk-r11-darwin-x86_64.zip'
  version '2'
  sha1 '7a6fdc0931ea9fe2713064f04474333369a34d53'
end
