# This file is autogenerated by the generate-sdks.sh script

require 'pathname'
require Pathname(__FILE__).realpath.dirname.join('../lib', 'android-tool-formula')

class AndroidBuildTools1700 < AndroidToolFormula
  url 'https://dl.google.com/android/repository/build-tools_r17-macosx.zip'
  version '17.0.0'
  sha1 '602ee709be9dbb8f179b1e4075148a57f9419930'

  depends_on "toonetown/android/android-sdk"
  depends_on "toonetown/android/android-platform-tools"

  def install
    (prefix/"build-tools"/version).install Dir["*"]
    install_tools prefix/"build-tools"/version

    link_sdk_dir "build-tools"
  end
  
end
