# This file is autogenerated by the generate-sdks.sh script

require 'pathname'
require Pathname(__FILE__).realpath.dirname.join('../lib', 'android-tool-formula')

class AndroidGapid < AndroidToolFormula
  url 'http://dl-ssl.google.com/android/repository/extras/gapid/gapid_r01_osx.zip'
  version '1.0.3'
  sha1 '597eb271349d890566274861eba2770a84ee4c69'
  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"extras/android/gapid").install Dir["*"]
    install_tools prefix/"extras/android/gapid"

    srcProp = prefix/"extras/android/gapid/source.properties"
    srcProp.delete if srcProp.exist?
    srcProp.write <<-EOS.undent
      Extra.VendorId=android
      Extra.Path=gapid
      Pkg.Revision=#{version}
    EOS

    link_sdk_dir "extras/android"
  end
  
end
