# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula") unless defined?(android_tool_formula)

class AndroidBuildTools2602 < AndroidToolFormula
  url "https://dl.google.com/android/repository/build-tools_r26.0.2-macosx.zip"
  version "26.0.2"
  sha1 "d9ed7c7f149ce38be5dc08979aea8acec1459ca0"

  depends_on "toonetown/android/android-sdk"
  depends_on "toonetown/android/android-platform-tools"

  def install
    (prefix/"build-tools"/version).install Dir["*"]
    install_tools prefix/"build-tools"/version

    link_sdk_dir "build-tools"
  end

  test do
    system "true"
  end
end
