# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula") unless defined?(android_tool_formula)

class AndroidBuildTools2501 < AndroidToolFormula
  url "https://dl.google.com/android/repository/build-tools_r25.0.1-macosx.zip"
  version "25.0.1"
  sha1 "7bf7f22d7d48ef20b6ab0e3d7a2912e5c088340f"

  depends_on "toonetown/android/android-sdk"
  depends_on "toonetown/android/android-platform-tools"

  def install
    (prefix/"build-tools"/version).install Dir["*"]
    install_tools prefix/"build-tools"/version

    link_sdk_dir "build-tools"
  end

  test do
    system "true"
  end
end
