# This file is autogenerated by the generate-sdks.sh script

require 'pathname'
require Pathname(__FILE__).realpath.dirname.join('../lib', 'android-tool-formula')

class AndroidSupport < AndroidToolFormula
  url 'http://dl-ssl.google.com/android/repository/support_r22.1.1.zip'
  version '22.1.1'
  sha1 '88bdc7b4074065ed28681f39e6b32c4f7ab45d94'
  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"extras/android/support").install Dir["*"]
    install_tools prefix/"extras/android/support"

    link_sdk_dir "extras/android"
  end
  
end
