# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula")

class AndroidBuildTools2112 < AndroidToolFormula
  url "https://dl.google.com/android/repository/build-tools_r21.1.2-macosx.zip"
  version "21.1.2"
  sha1 "e7c906b4ba0eea93b32ba36c610dbd6b204bff48"

  depends_on "toonetown/android/android-sdk"
  depends_on "toonetown/android/android-platform-tools"

  def install
    (prefix/"build-tools"/version).install Dir["*"]
    install_tools prefix/"build-tools"/version

    link_sdk_dir "build-tools"
  end

  test do
    system "true"
  end
end
