# This file is autogenerated by the generate-sdks.sh script

require 'pathname'
require Pathname(__FILE__).realpath.dirname.join('../lib', 'android-tool-formula')

class AndroidDocs < AndroidToolFormula
  url 'http://dl-ssl.google.com/android/repository/docs-21_r01.zip'
  version '21-r1'
  sha1 '1c71f97ffb97e77120c1a73c8a29d3783c65f86d'

  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"docs").install Dir["*"]
    install_tools prefix/"docs"
    link_sdk_dir "docs"
  end
  
end
