# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula") unless defined?(android_tool_formula)

class GoogleMarketApkExpansion < AndroidToolFormula
  desc "Android Market APK Expansion library"
  url "https://dl.google.com/android/repository/market_apk_expansion-r03.zip"
  version "1"
  sha1 "5305399dc1a56814e86b8459ce24871916f78b8c"
  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"extras/google/market_apk_expansion").install Dir["*"]
    install_tools prefix/"extras/google/market_apk_expansion"

    src_prop = prefix/"extras/google/market_apk_expansion/source.properties"
    src_prop.delete if src_prop.exist?
    src_prop.write <<-EOS.undent
      Extra.VendorId=google
      Extra.Path=market_apk_expansion
      Pkg.Revision=#{version}
    EOS

    link_sdk_dir "extras/google"
  end

  test do
    system "true"
  end
end
