# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula") unless defined?(android_tool_formula)

class GoogleInstantapps < AndroidToolFormula
  desc "Android Instant Apps Development SDK"
  url "https://dl.google.com/android/repository/aiasdk-1.0.0.zip"
  version "1.0.0"
  sha1 "50074a0f0312ee1d0d81d2cddc3d84a8a9e97a53"
  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"extras/google/instantapps").install Dir["*"]
    install_tools prefix/"extras/google/instantapps"

    src_prop = prefix/"extras/google/instantapps/source.properties"
    src_prop.delete if src_prop.exist?
    src_prop.write <<-EOS.undent
      Extra.VendorId=google
      Extra.Path=instantapps
      Pkg.Revision=#{version}
    EOS

    link_sdk_dir "extras/google"
  end

  test do
    system "true"
  end
end
