# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula") unless defined?(android_tool_formula)

class GoogleAdmobAdsSdk < AndroidToolFormula
  desc "AdMob Ads SDK"
  url "https://dl.google.com/android/repository/GoogleAdMobAdsSdkAndroid-6.4.1.zip"
  version "11"
  sha1 "0102859d9575baa0bf4fd5eb422af2ad0fe6cb82"
  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"extras/google/admob_ads_sdk").install Dir["*"]
    install_tools prefix/"extras/google/admob_ads_sdk"

    src_prop = prefix/"extras/google/admob_ads_sdk/source.properties"
    src_prop.delete if src_prop.exist?
    src_prop.write <<-EOS.undent
      Extra.VendorId=google
      Extra.Path=admob_ads_sdk
      Pkg.Revision=#{version}
    EOS

    link_sdk_dir "extras/google"
  end

  test do
    system "true"
  end
end
