# This file is autogenerated by the generate-sdks.sh script

require 'pathname'
require Pathname(__FILE__).realpath.dirname.join('../lib', 'android-tool-formula')

class GoogleAdmobAdsSdk < AndroidToolFormula
  url 'https://dl-ssl.google.com/googleadmobadssdk/googleadmobadssdkandroid-6.4.1.zip'
  version '11'
  sha1 '0102859d9575baa0bf4fd5eb422af2ad0fe6cb82'
  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"extras/google/admob_ads_sdk").install Dir["*"]
    install_tools prefix/"extras/google/admob_ads_sdk"

    srcProp = prefix/"extras/google/admob_ads_sdk/source.properties"
    srcProp.delete if srcProp.exist?
    srcProp.write <<-EOS.undent
      Extra.VendorId=google
      Extra.Path=admob_ads_sdk
      Pkg.Revision=#{version}
    EOS

    link_sdk_dir "extras/google"
  end
  
end
