# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula")

class GooglePlayServicesFroyo < AndroidToolFormula
  desc "Google Play services client library and sample code"
  url "https://dl.google.com/android/repository/google_play_services_3265130_r12.zip"
  version "12"
  sha1 "92558dbc380bba3d55d0ec181167fb05ce7c79d9"
  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"extras/google/google_play_services_froyo").install Dir["*"]
    install_tools prefix/"extras/google/google_play_services_froyo"

    src_prop = prefix/"extras/google/google_play_services_froyo/source.properties"
    src_prop.delete if src_prop.exist?
    src_prop.write <<-EOS.undent
      Extra.VendorId=google
      Extra.Path=google_play_services_froyo
      Pkg.Revision=#{version}
    EOS

    link_sdk_dir "extras/google"
  end

  test do
    system "true"
  end
end
