# This file is autogenerated by the generate-sdks.sh script

require 'pathname'
require Pathname(__FILE__).realpath.dirname.join('../lib', 'android-tool-formula')

class GoogleAuto < AndroidToolFormula
  url 'http://dl-ssl.google.com/android/repository/extras/auto/desktop-head-unit-linux_r01.zip'
  version '1.0'
  sha1 'e054563f9efdc2f6089693566bce5b8fba2cd1c6'
  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"extras/google/auto").install Dir["*"]
    install_tools prefix/"extras/google/auto"

    srcProp = prefix/"extras/google/auto/source.properties"
    srcProp.delete if srcProp.exist?
    srcProp.write <<-EOS.undent
      Extra.VendorId=google
      Extra.Path=auto
      Pkg.Revision=#{version}
    EOS

    link_sdk_dir "extras/google"
  end
  
end
