# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula")

class GoogleWebdriver < AndroidToolFormula
  url "https://dl.google.com/android/repository/webdriver_r02.zip"
  version "2"
  sha1 "13f3a3b2670a5fc04a7342861644be9a01b07e38"
  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"extras/google/webdriver").install Dir["*"]
    install_tools prefix/"extras/google/webdriver"

    src_prop = prefix/"extras/google/webdriver/source.properties"
    src_prop.delete if src_prop.exist?
    src_prop.write <<-EOS.undent
      Extra.VendorId=google
      Extra.Path=webdriver
      Pkg.Revision=#{version}
    EOS

    link_sdk_dir "extras/google"
  end

  test do
    system "true"
  end
end
