# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula")

class GoogleGcm < AndroidToolFormula
  desc "GCM library has been moved to Google Play Services (com.google.android.gms.gcm) and this standalone version is no longer supported"
  url "https://dl.google.com/android/repository/gcm_r03.zip"
  version "3"
  sha1 "ad066fd0dc7fc99d8aadac09c65a3c2519fbc7bf"
  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"extras/google/gcm").install Dir["*"]
    install_tools prefix/"extras/google/gcm"

    src_prop = prefix/"extras/google/gcm/source.properties"
    src_prop.delete if src_prop.exist?
    src_prop.write <<-EOS.undent
      Extra.VendorId=google
      Extra.Path=gcm
      Pkg.Revision=#{version}
    EOS

    link_sdk_dir "extras/google"
  end

  test do
    system "true"
  end
end
