# This file is autogenerated by the generate-sdks.sh script

require 'pathname'
require Pathname(__FILE__).realpath.dirname.join('../lib', 'android-tool-formula')

class GoogleUsbDriver < AndroidToolFormula
  url 'http://dl-ssl.google.com/android/repository/usb_driver_r11-windows.zip'
  version '11'
  sha1 'dc8a2ed2fbd7246d4caf9ab10ffe7749dc35d1cc'
  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"extras/google/usb_driver").install Dir["*"]
    install_tools prefix/"extras/google/usb_driver"

    srcProp = prefix/"extras/google/usb_driver/source.properties"
    srcProp.delete if srcProp.exist?
    srcProp.write <<-EOS.undent
      Extra.VendorId=google
      Extra.Path=usb_driver
      Pkg.Revision=#{version}
    EOS

    link_sdk_dir "extras/google"
  end
  
end
