# This file is autogenerated by the generate-sdks.sh script

require 'pathname'
require Pathname(__FILE__).realpath.dirname.join('../lib', 'android-tool-formula')

class GoogleAnalyticsSdkV2 < AndroidToolFormula
  url 'https://dl.google.com/android/repository/GoogleAnalyticsAndroid_2.0beta5.zip'
  version '3'
  sha1 'dc14026bf0ce78315cb5dd00552607de0894de83'
  depends_on "toonetown/android/android-sdk"

  def install
    (prefix/"extras/google/analytics_sdk_v2").install Dir["*"]
    install_tools prefix/"extras/google/analytics_sdk_v2"

    srcProp = prefix/"extras/google/analytics_sdk_v2/source.properties"
    srcProp.delete if srcProp.exist?
    srcProp.write <<-EOS.undent
      Extra.VendorId=google
      Extra.Path=analytics_sdk_v2
      Pkg.Revision=#{version}
    EOS

    link_sdk_dir "extras/google"
  end
  
end
